plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

def exportVersion = "${project.mod_version}-${project.minecraft_version}"
def exportBaseName = "${project.archives_base_name}-${exportVersion}"

tasks.named("jar") {
    archiveFileName.set("${exportBaseName}-dev.jar")
}

tasks.named("remapJar") {
    archiveFileName.set("${exportBaseName}.jar")
}

repositories {
    maven { url "https://maven.shedaniel.me/" }         // For Cloth Config
    maven { url "https://maven.terraformersmc.com/" }   // For Mod Menu
    maven { url "https://maven.nucleoid.xyz/" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.findProperty('minecraft_version')}"
    mappings "net.fabricmc:yarn:${project.findProperty('yarn_mappings')}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.findProperty('loader_version')}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.findProperty('fabric_api_version')}"

    // Optional dependencies – compile only, not included in jar
    modImplementation "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}"
    modCompileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21

    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

sourceSets.main.java.srcDirs = [
        'src/main/java',
        rootProject.file('modules/common/src/main/java')
]
sourceSets.main.resources.srcDirs = [
        'src/main/resources',
        rootProject.file('modules/common/src/main/resources')
]

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.findProperty('minecraft_version')

    filesMatching("fabric.mod.json") {
        expand(
                "version": project.version,
                "minecraft_version": project.findProperty('minecraft_version')
        )
    }
}
